
["Damage Popup Configuration"]
	#Should show onomatopoeia expressions in popup particle?
	"Show Expressions" = true
	#Should text include outlines?
	"Show Text Outline" = true
	#Should show damage counter in popup particle?
	"Show Damage Counter" = true
	#Size multiplier for the hit particle popups.
	#Range: 0.0 ~ 1.7976931348623157E308
	"Size Multiplier" = 0.6
	#The decimal format for the popup damage text.
	#e.g.: [0.000] will result in numbers like 7.325 while just [0] keeps it as whole numbers.
	"Damage Decimal Format" = "0.00!"
	#RGB Color values for critical hit popups.
	"Critical Hit Popup Colors" = [206, 1, 1]
	#RGB Color values for heal popups.
	"Heal Popup Colors" = [0, 255, 38]
	#RGB Color values for magic attack popups.
	"Melee Hit Popup Colors" = [255, 132, 132]
	#RGB Color values for other damage type popups (becomes redder the higher the damage).
	"Generic Popup Colors" = [255, 253, 159]
	#A list of onomatopoeia expressions for melee hit popups.
	"Melee Expressions" = ["Nice!", "Pow!", "Good Job!", "Ouchies!", "Wham!", "Thwack!", "Bonkk!", "Smack!", "Boom!", "Bam!", "Boop!", "Sliced that bum!", "Bloody!"]
	#A list of onomatopoeia expressions for critical melee hit popups.
	"Critical Melee Expressions" = ["GRAAH!", "LETHAL!", "KABOOM!", "SMACKED YO ASS!", "SMASH!", "ERASED!", "DEVASTATED!", "ANNIHILATE!", "DECIMATE!", "DESTROYED!", "OOF!", "GOODBYE!", "SQUISH!", "VITAL!", "EXACT!", "EAT SHIT!", "TRASH!", "SKILL ISSUE!", "GET REKT!", "BYE BITCH!", "PATHETIC!", "JESUS!", "CLEAN CUT!", "FOLDED!", "SIT DOWN DOG!", "WASTED!", "DIE!", "ERASED FROM THE VERY EXISTENCE ITSELF!", "U FUCKING AWESOME!", "BUILT-DIFFERENT!"]
	#A list of onomatopoeia expressions for critical arrow effect popups.
	"Critical Arrow Expressions" = ["HOLY SHIT!", "SPLIT-OPEN-HEAD!", "H-H-HEADSHOT!", "PIERCED THAT EMPTY ASS BRAIN!", "SNIPED EZ!", "AIMBOT?", "BRAIN SURGERY!", "LOBOTOMIZED!", "MIND BLOWN!", "SOCIAL DISTANCING!", "WHERE U AT?", "DODGE THIS!", "SLEEP TIGHT!", "MIND-BLOWING!", "HOW'D U DO THAT?!", "U COOKING!", "WOAH!", "BEST SHOT EVER? no.", "NATURAL TALENT!"]

["Hurt Overlay Configuration"]
	#Configure the conditions to enable the entity white hurt overlay.
	#Allowed Values: DEFAULT, ONLY_BY_PLAYER, DISABLED
	"Hurt Overlay Condition" = "DEFAULT"

["Special Sounds Configuration"]
	#Should play sounds on weapon swing?
	"Swinging Sounds" = true

